In [4]:
############### PANDAS ###############


In [5]:
import numpy as np
import pandas as pd

In [6]:
data = pd.Series([0.25,0.5,0.75,1,0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
4    0.00
dtype: float64


In [7]:
print(data.values)
type(data)

[0.25 0.5  0.75 1.   0.  ]


pandas.core.series.Series

In [18]:
data = pd.Series([0.25,0.5,0.75,1.0],
    index=['a','b','c','d'])
data['b']

0.5

In [19]:
population_dict = {
    "California": 38332521,
    "Texas": 2644,
    "New York": 19,
    "Florida": 19552860,
    "Illinois": 12882135,
    }
population = pd.Series(population_dict)
population

California    38332521
Texas             2644
New York            19
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['California':'Florida']

California    38332521
Texas             2644
New York            19
Florida       19552860
dtype: int64

In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas             2644  695662
New York            19  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas             2644
New York            19
Florida       19552860
Illinois      12882135

In [ ]:
# Derive dataframe from a dictionary with a mathematical operation
data = [{'a':i, 'b':2*i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [ ]:
pd.DataFrame([{'a':1, 'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'], 
            index=['a','b','c'])

foo       bar
a  0.177303  0.594651
b  0.012558  0.577173
c  0.540785  0.016382

In [ ]:
############### DATA INDEXING AND SLICING ###############

In [ ]:
data = pd.Series([0.25,0.50,0.75,1.0],
        index = ['a','b','c','d'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [ ]:
'a' in data

True

In [ ]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [ ]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [ ]:
data[['a','d']]   #birden fazla varsa iki bracket lazim ki liste olsun

a    0.25
d    1.00
dtype: float64

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data.loc[:'New York',:'area']

area
California  423967
Texas       695662
New York    141297

In [ ]:
data.iloc [1:3]  # iloc allows us to use index to locate

b    0.50
c    0.75
dtype: float64

In [ ]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
############### OPERATING ON DATA IN PANDAS ###############

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4)) # 4u shape olarak tanimliyorum
ser

0    6
1    3
2    7
3    4
dtype: int64

In [ ]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [ ]:
np.exp(ser) #exponential, e^number 

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [ ]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [ ]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [ ]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [ ]:
area.index.union(population.index) # same as writing: area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
A.add(B, fill_value=0) # instead of NaN, it will give the number that exists in either series

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [ ]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),
                columns=list('AB'))
A

A   B
0   9  15
1  14  14

In [ ]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  2  6  3
1  8  2  4
2  2  6  4

In [ ]:
A + B

A     B   C
0  15.0  17.0 NaN
1  16.0  22.0 NaN
2   NaN   NaN NaN

In [ ]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  15.0  17.0  16.0
1  16.0  22.0  17.0
2  19.0  15.0  17.0

In [ ]:
############### PYTHON OPERATOR:PANDAS ###############

'''add(), sub(), subtract()
    mul(), multiply() 
    / truediv(), div(), divide() // floordiv() 
    % mod() ** pow()'''

In [ ]:
A = rng.randint(10, size=(3,4))
A

array([[8, 6, 1, 3],
       [8, 1, 9, 8],
       [9, 4, 1, 3]])

In [ ]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0, -5,  8,  5],
       [ 1, -2,  0,  0]])

In [ ]:
df.iloc[0]

Q    8
R    6
S    1
T    3
Name: 0, dtype: int64

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -5  8  5
2  1 -2  0  0

In [ ]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  2  0 -5 -3
1  7  0  8  7
2  5  0 -3 -1

In [ ]:
############### HANDLING MISSING DATA ###############

In [ ]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [ ]:
for dtype in ['object', 'int']:
    print("dtyppe =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtyppe = object
41.4 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtyppe = int
575 µs ± 2.07 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



In [ ]:
1E6

1000000.0

In [ ]:
x=5
y=3

%timeit z = x + y
print()

x = 'ahmet'
y = 'mehmet'

%timeit z = x + y
print()

35.8 ns ± 0.273 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

63.6 ns ± 0.526 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)



In [ ]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0*np.nan

nan

In [ ]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [ ]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [ ]:
x = pd.Series(range(2), dtype=float)
x

0    0.0
1    1.0
dtype: float64

In [ ]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])

In [ ]:
data.isnull() #gives an index, can create an if statement in loop

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
data.dropna

<bound method Series.dropna of 0        1
1      NaN
2    hello
3     None
dtype: object>

In [ ]:
df = pd.DataFrame([[1,   np.nan, 2],
                 [2,    3,      5],
                 [np.nan, 4,    6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna() # gave the row with no NaN

0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [ ]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.dropna(axis='columns', how='all') #drop if all are NaN

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna(axis='columns', how='any')

2
0  2
1  5
2  6

In [ ]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [ ]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
# forward-fill
data.fillna(method='ffill')   # fill NaN with what is before it

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [ ]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0